"""Initial revision

Revision ID: 17253afc4adf
Revises: 
Create Date: 2018-12-04 13:34:55.444831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17253afc4adf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
